open-id-connect:
  redirect-uri: http://localhost:4567/api/auth/code
  discovery-document-uri: https://accounts.google.com/.well-known/openid-configuration
  client-id: 241147659016-m5tbp8dgmmmpun4t9415ofvipdthccoi.apps.googleusercontent.com
  secret: ae7ftmx7fnLdsX6FNx53S5HI

spring.datasource.url: jdbc:h2:./10poengsappen